services:
  - type: web
    name: car-rental-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn car_rental_system.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 0leh#)6s$#u7(25=ng8xa-+oq%-s)$nol2s-@ze%^-$^ubux@#
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: drivenow-db 
          property: connectionString

databases:
  - name: drivenow-db
    plan: free
