services:
  - type: web
    name: car-rental-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn car_rental_system.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: l_-rzgafsu&idtdvkez3-_l@#+$6g1sr_$rn99#51$)ff^giqi
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: drivenow-g8je.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: drivenow-db
          property: connectionString

databases:
  - name: drivenow-db
    plan: free
