services:
  - type: web
    name: car-rental-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn car_rental_system.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: car_rental_system.settings
      - key: SECRET_KEY
        value: i3%7v46^#ly^2fpgs&&u-w@qj&c0+m_imhkentndqn6@5q)b-3
      - key: ALLOWED_HOSTS
        value: your-backend.onrender.com
